services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-ssr-prod:latest
    env_file:
      - .env.production
    ports:
      - "3000:3000" # Mapea el puerto 3000 de tu PC de producción al 3000 del contenedor
    restart: always
    environment:
      - NODE_ENV=production
